spring.application.name=ExpenseTracker
server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/ExpenseTracker?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# OPENAI KEY (you must add)
openai.api.key=${OPENAI_API_KEY}
openai.model=gpt-4o-mini
