spring.application.name=ExpenseTracker
server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/ExpenseTracker?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# OPENAI KEY (you must add)
openai.api.key=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
openai.model=gpt-4o-mini